name: Build mender package
on:
  workflow_dispatch:
    inputs:
      distribution_release:
        description: 'Debian distribution release'
        required: true
        default: 'bookworm'
      package_name:
        description: 'Name of package (e.g. mender-client, mender-connect or mender-configure)'
        required: true
      package_version:
        description: 'Version of package (e.g. 2.1.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Check out the mender-dist-packages repository
        uses: actions/checkout@v3
        with:
          repository: mendersoftware/mender-dist-packages
          ref: master
          path: mender-dist-packages
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Upload package to packagecloud repository
#        run: ./.github/scripts/upload-kernel-packages-packagecloud "${PACKAGECLOUD_USER}" "${PACKAGECLOUD_REPOSITORY}" debian "${{ inputs.distribution_release }}"
#        env:
#          PACKAGECLOUD_USER: ${{ secrets.PACKAGECLOUD_USER }}
#          PACKAGECLOUD_REPOSITORY: ${{ secrets.PACKAGECLOUD_REPOSITORY }}
#          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
