name: Build mender package
on:
  workflow_dispatch:
    inputs:
      edi_pi_repository_branch:
        description: 'Branch of edi-pi repository'
        required: true
        default: 'master'
      package_name:
        description: 'Name of package (e.g. mender-client, mender-connect or mender-configure)'
        required: true
      package_version:
        description: 'Version of package (e.g. 2.1.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Check out the edi-pi repository
        uses: actions/checkout@v4
        with:
          repository: lueschem/edi-pi
          ref: ${{ inputs.edi_pi_repository_branch }}
          path: edi-pi
      - name: Check out the mender-dist-packages repository
        uses: actions/checkout@v4
        with:
          repository: mendersoftware/mender-dist-packages
          ref: master
          path: mender-dist-packages
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Mender packages
        run: ./.github/scripts/build-mender-packages "${{ inputs.package_name }}" "${{ inputs.package_version }}"
      - name: Upload package to packagecloud repository
        run: ./.github/scripts/upload-mender-packages-packagecloud "${PACKAGECLOUD_USER}" "${PACKAGECLOUD_REPOSITORY}" debian "${{ inputs.package_name }}"
        env:
          PACKAGECLOUD_USER: ${{ secrets.PACKAGECLOUD_USER }}
          PACKAGECLOUD_REPOSITORY: ${{ secrets.PACKAGECLOUD_REPOSITORY }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
