name: Build and dispatch OS image to device
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'edi project repository'
        required: true
        default: 'edi-pi'
      repository_version:
        description: 'branch/version of edi project repository'
        required: true
        default: 'master'
      configuration:
        description: 'OS image configuration'
        required: true
        default: 'pi4-bullseye-arm64.yml'
      device_id:
        description: 'Mender device ID'
        required: true

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Check out the source code of this repository
        uses: actions/checkout@v3
      - name: Check out the source code of the edi project repository
        uses: actions/checkout@v3
        with:
          repository: '${{ github.repository_owner }}/${{ github.event.inputs.repository }}'
          ref: '${{ github.event.inputs.repository_version }}'
          path: 'edi_project_repository'
      - name: Create the OS artifact
        run: cd edi_project_repository && sudo edi -v image create ${{ github.event.inputs.configuration }}
