name: Test OS setup
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'edi project repository'
        required: true
        default: 'edi-pi'
      repository_version:
        description: 'branch/version of edi project repository'
        required: true
        default: 'master'
      configuration:
        description: 'OS image configuration'
        required: true
        default: 'pi4-bullseye-arm64-gitops.yml'
      device_id:
        description: 'Mender device ID'
        required: true

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Print summary of job
        run: echo "${{ inputs.repository }}/${{ inputs.repository_version }}:${{ inputs.configuration }} --> ${{ inputs.device_id }}"
      - name: Check out the source code of this repository
        uses: actions/checkout@v3
      - name: Run tests on the device
        run: ./run-tests ${{ inputs.device_id }} ${{ inputs.repository }}
        env:
          MENDER_ACCESS_TOKEN: ${{ secrets.MENDER_ACCESS_TOKEN }}
          DEVICE_SECRETS: ${{ secrets.DEVICE_SECRETS }}
